#title in header
title: "í‚¤ìœ„ íŒ€ë¸”ë¡œê·¸"

#main info
#owner
owner: "kiwi. team blog"
email: red@kiwi.today
info: "í‚¤ìœ„ íŒ€ë¸”ë¡œê·¸ì…ë‹ˆë‹¤. ê°œë°œí•˜ë©° ì‚¬ìš©í•˜ëŠ” ê¸°ìˆ ë“¤, ì›ë‹¨ ê´€ë ¨ ì •ë³´ë“± í‚¤ìœ„ì„œë¹„ìŠ¤ë¥¼ ê°œë°œ/ìš´ì˜í•˜ë©´ì„œ ì •ë¦¬ëœ ì •ë³´ë“¤ì´ ê³µìœ ë©ë‹ˆë‹¤."
#description
desc: "í‚¤ìœ„ëŠ” ë¬´ì—‡ì¸ê°€ìš”? ğŸ’¡ ë™ëŒ€ë¬¸ì¢…í•©ì‹œì¥ì„ ì¤‘ì‹¬ìœ¼ë¡œ ì›ë‹¨ ê´€ë ¨ ì •ë³´ë¥¼ ì œê³µí•©ë‹ˆë‹¤."

#menu
# menu:
#   Works: /Works
#   About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
# tcolor: FFC80F
tcolor: FF6600

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/adisaktijrs
linkedin: https://linkedin.com/in/adisaktijrs
twitter: https://twitter.com/adisaktijrs
instagram: https://instagram.com/adisaktijrs
stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
